# Created using YamlCreate.ps1 v1.1.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: PrestonN.FreeTube
PackageVersion: 0.14.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.14.0-beta/freetube-0.14.0-setup-x64.exe
  InstallerSha256: b767f421917de075a38381f6495e5bbb5ba058b25d1fa3145ffa714919743f71
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

© 2021 GitHub, Inc.